In [1]:
from data_loader import load_data

In [2]:
%run main.py

reading rating file ...
splitting dataset ...
reading KG file ...
data loaded.


In [3]:
data

(6036, 2347, 47331, 23, array([[   0, 1159,    1],
        [   0, 1314,    1],
        [   0,  162,    1],
        ...,
        [6035, 2239,    0],
        [6035, 1084,    0],
        [6035, 1325,    0]], dtype=int32), array([[ 263, 1804,    1],
        [3679, 1138,    1],
        [2019, 1377,    1],
        ...,
        [2026, 1505,    0],
        [5439, 2063,    0],
        [1178,  887,    1]], dtype=int32), array([[1447,  974,    1],
        [3642,  544,    1],
        [3017, 1346,    1],
        ...,
        [2375, 1576,    0],
        [ 215,  957,    1],
        [3686, 2173,    1]], dtype=int32), array([[    0,     8, 15440],
        [    0,     8, 15441],
        [    0,     8, 15442],
        ...,
        [ 6729,     8, 41101],
        [ 6729,    10, 47330],
        [ 6729,    18, 15481]], dtype=int32))

In [4]:
#n_user
data[0]

6036

In [5]:
#n_item
data[1]

2347

In [6]:
#n_entity
data[2]

47331

In [7]:
#n_relation
data[3]

23

In [8]:
#train_data
data[4]

array([[   0, 1159,    1],
       [   0, 1314,    1],
       [   0,  162,    1],
       ...,
       [6035, 2239,    0],
       [6035, 1084,    0],
       [6035, 1325,    0]], dtype=int32)

In [9]:
max(data[4][0:,1])

2346

In [10]:
#eval_data
data[5]

array([[ 263, 1804,    1],
       [3679, 1138,    1],
       [2019, 1377,    1],
       ...,
       [2026, 1505,    0],
       [5439, 2063,    0],
       [1178,  887,    1]], dtype=int32)

In [11]:
max(data[5][0:,1])

2346

In [12]:
#test_data
data[6]

array([[1447,  974,    1],
       [3642,  544,    1],
       [3017, 1346,    1],
       ...,
       [2375, 1576,    0],
       [ 215,  957,    1],
       [3686, 2173,    1]], dtype=int32)

In [13]:
max(data[6][0:,1])

2346

In [14]:
#kg
data[7]

array([[    0,     8, 15440],
       [    0,     8, 15441],
       [    0,     8, 15442],
       ...,
       [ 6729,     8, 41101],
       [ 6729,    10, 47330],
       [ 6729,    18, 15481]], dtype=int32)

In [15]:
max(data[7][0:,0])

6729

In [16]:
import tensorflow as tf

x = tf.placeholder("float", None)
y = x * 2

with tf.Session() as session:
    result = session.run(y, feed_dict={x: [1, 2, 3]})
    print(result)

[2. 4. 6.]


In [17]:
type(result)

numpy.ndarray